"""Unified command-line entry point for the AIVE toolkit.

Exposes the three loop stages behind one command:

    aive scan   <path> [--output F] [--min-confidence X] [--fail-on SEV]
    aive plan   <findings.json> [--output F]
    aive verify <path> [--json] [--strict]

The standalone scripts in ``scripts/`` remain for the GitHub Actions workflow;
this module is what ``pip install`` wires up as the ``aive`` console command.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from . import __version__
from .engine import (
    SEVERITY_ORDER,
    build_patch_plan_markdown,
    build_scan_payload,
    run_verification,
)

SEVERITY_CHOICES = ("low", "medium", "high")


def _write_or_print(rendered: str, output: str | None) -> None:
    if output:
        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered + "\n", encoding="utf-8")
    else:
        print(rendered)


def _run_scan(args: argparse.Namespace) -> int:
    target = Path(args.target).resolve()
    payload = build_scan_payload(target, min_confidence=args.min_confidence)
    _write_or_print(json.dumps(payload, indent=2), args.output)

    if args.fail_on:
        threshold = SEVERITY_ORDER[args.fail_on]
        breached = any(
            SEVERITY_ORDER.get(str(finding["severity"]), 0) >= threshold
            for finding in payload["findings"]
        )
        if breached:
            return 1
    return 0


def _run_plan(args: argparse.Namespace) -> int:
    payload = json.loads(Path(args.findings_file).read_text(encoding="utf-8"))
    _write_or_print(build_patch_plan_markdown(payload), args.output)
    return 0


def _run_verify(args: argparse.Namespace) -> int:
    target = Path(args.target).resolve()
    checks = run_verification(target)
    if args.json:
        print(json.dumps([check.to_dict() for check in checks], indent=2))
    else:
        for check in checks:
            print(f"- {check.name}: {check.status} ({check.details})")
    failed = any(check.status == "fail" for check in checks)
    return 1 if args.strict and failed else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="aive", description="AIVE exploit-to-patch toolkit.")
    parser.add_argument("--version", action="version", version=f"aive {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    scan = sub.add_parser("scan", help="Scan a repository and emit a findings payload.")
    scan.add_argument("target", nargs="?", default=".", help="Repository path to scan.")
    scan.add_argument("--output", help="Optional file to write JSON payload to.")
    scan.add_argument("--min-confidence", type=float, default=0.0, help="Drop findings below this confidence.")
    scan.add_argument("--fail-on", choices=SEVERITY_CHOICES, help="Exit non-zero at this severity or higher.")
    scan.set_defaults(func=_run_scan)

    plan = sub.add_parser("plan", help="Render a patch plan from a findings payload.")
    plan.add_argument("findings_file", help="Path to the JSON payload generated by scan.")
    plan.add_argument("--output", help="Optional file to write markdown output to.")
    plan.set_defaults(func=_run_plan)

    verify = sub.add_parser("verify", help="Run lightweight verification checks.")
    verify.add_argument("target", nargs="?", default=".", help="Repository path to verify.")
    verify.add_argument("--json", action="store_true", help="Emit JSON instead of text.")
    verify.add_argument("--strict", action="store_true", help="Exit non-zero when any check fails.")
    verify.set_defaults(func=_run_verify)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
