#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from aive.engine import build_patch_plan_markdown


def main() -> int:
    parser = argparse.ArgumentParser(description="Render an AIVE patch plan from a findings payload.")
    parser.add_argument("findings_file", help="Path to the JSON payload generated by scan_repo.py.")
    parser.add_argument("--output", help="Optional file to write markdown output to.")
    args = parser.parse_args()

    findings_path = Path(args.findings_file)
    payload = json.loads(findings_path.read_text(encoding="utf-8"))
    rendered = build_patch_plan_markdown(payload)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered + "\n", encoding="utf-8")
    else:
        print(rendered)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
